# Site settings
title: Live Japanese TV
email: Ethan@Sucks.com
description: > # Ethan Sucks
baseurl: "/Weaboo/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


# Layout settings
header_type: default # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Donate
    link: #Insert ButtCoin link
  option2:
    name: Fuck Josh
    link: www.myawesomelink.com



# Build settings
markdown: kramdown
